version: '3.8'

services:
  mpd-hls:
    image: charmingcheung000/mpd-hls:latest
    container_name: mpd-hls
    ports:
      - "0.0.0.0:9100:9100"
      - "[::]:9100:9100"
    environment:
      - RUST_LOG=INFO
      - TZ=Asia/Shanghai
      - _RJEM_MALLOC_CONF=narenas:2,background_thread:true,dirty_decay_ms:5000,muzzy_decay_ms:5000
    volumes:
      - /opt/mpd-hls/var:/app/var
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
